name: continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Build and test
        run: ./mvnw clean verify
